import Container from "@/components/Container";

export default function NzLawSocietyAiGuidanceArticlePage() {
  return (
    <Container className="py-16">
      <article className="mx-auto max-w-4xl rounded-panel border border-[#d7e4fb] bg-white p-6 shadow-panel md:p-10">
        <header>
          <h1 className="text-4xl font-semibold text-[#10243F]">
            What New Zealand&apos;s Law Society Guidance Really Means for Your Firm&apos;s AI Journey
          </h1>
          <p className="mt-3 text-sm uppercase tracking-[0.1em] text-[#355f95]">Insights | March 2024</p>
        </header>

        <div className="mt-8 space-y-6 text-[1.04rem] leading-8 text-slate-700">
          <p>
            The New Zealand Law Society Te Kahui Ture o Aotearoa has released its first dedicated guidance on Generative AI for
            the legal profession. It is a measured, practical document and if you are a lawyer thinking about where AI fits into
            your practice, it is worth understanding what it is actually telling you.
          </p>

          <p>Here is our read of the key themes.</p>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#10243F]">The profession is expected to engage, not wait</h2>
            <p>
              The guidance does not counsel caution for caution&apos;s sake. It opens by acknowledging that lawyers across New Zealand
              and overseas are already using and investing in AI to enhance their service offering. The Law Society&apos;s position is
              clear: this is a technology that deserves serious attention, and firms that understand it will be better placed than
              those who do not.
            </p>
            <p>
              At the same time, the guidance is candid that the opportunities come with specific, manageable risks. The message is
              not &quot;slow down&quot;, it is &quot;go in with your eyes open.&quot;
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#10243F]">Your professional obligations do not pause for AI</h2>
            <p>
              Perhaps the most significant theme running through the guidance is continuity of responsibility. A lawyer who uses AI
              to draft a contract or conduct research remains fully responsible for the quality of that output. The fact that it
              was generated by an algorithm provides no defence against a complaint or disciplinary proceeding.
            </p>
            <p>
              This matters practically. AI tools can produce outputs that appear authoritative but contain errors, a phenomenon the
              guidance describes as &quot;hallucination.&quot; Courts in New Zealand have already flagged this risk, urging judicial officers
              and support staff to scrutinise submissions that appear to have been AI-generated. Lawyers need robust review
              processes, not just good prompts.
            </p>
            <p>
              The guidance also highlights specific rules under the Lawyers and Conveyancers Act (Conduct and Client Care) Rules
              2008 that come into play, including duties of competence (r 3), prohibition on misleading conduct (r 10.9), and
              fidelity to the court (r 13.1). Supervisors have additional exposure if staff are using AI tools in unauthorised or
              unmonitored ways.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#10243F]">
              Privacy and confidentiality require careful structural thinking
            </h2>
            <p>
              New Zealand currently has no overarching AI regulation, but existing law applies and the Privacy Act carries real
              weight here. When data is input into a third-party AI tool, that data may be visible to the provider, may be used
              for training, and may be transferred to servers located overseas. Each of these scenarios engages the Privacy Act,
              and Information Privacy Principle 12 specifically governs disclosure outside New Zealand.
            </p>
            <p>
              Both the government&apos;s public service guidance and the Courts&apos; own AI guidelines caution strongly against feeding
              personal or confidential information into external AI tools. The Law Society echoes this. The practical implication
              for firms is that data governance, what can go in, what cannot, and how that is enforced, needs to be defined before
              a tool is deployed, not after.
            </p>
            <p>
              Legal privilege is also at stake. Inputting privileged material into a publicly accessible AI tool may constitute a
              breach of privilege. Fictional or anonymised data should be used for testing and template generation.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#10243F]">Intellectual property questions are live and unsettled</h2>
            <p>
              Ownership of AI-generated content is not a settled question in New Zealand law, and the guidance flags it as an
              active risk area. Some AI tools &quot;scrape&quot; content from external sources, which can raise copyright concerns. Separately,
              some terms of service allow providers to retain ownership of output data or to reuse your inputs, provisions that
              could place a lawyer in breach of professional obligations if they involve client or privileged material.
            </p>
            <p>Reading the fine print in vendor contracts is not optional. It is part of due diligence.</p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#10243F]">Fee structures and client disclosure need to evolve</h2>
            <p>
              The guidance raises a question that will become increasingly pressing as AI adoption grows: how should firms bill for
              work assisted or completed by AI?
            </p>
            <p>
              On the time and attendance model, lawyers are asked to consider what is appropriate when a non-human is performing
              tasks that were previously billed by the hour. The guidance suggests that billing for AI-assisted research might be
              analogous to billing for use of a research tool, but that charging a full hourly rate for AI-generated contract
              drafting or document review warrants more careful thought.
            </p>
            <p>
              Related to this is the question of transparency. Lawyers have professional obligations to inform clients about how
              their work will be carried out and by whom. Whether and when to disclose the use of AI, and whether client consent
              is required, are questions firms will need to address in their engagement letters and client care information.
            </p>
          </section>

          <section className="space-y-4">
            <h2 className="text-2xl font-semibold text-[#10243F]">
              A structured approach is what the guidance is really asking for
            </h2>
            <p>
              Underlying all of the specific risk areas is a consistent call for firms to approach AI the way they would approach
              any significant operational change: with a plan. That means vendor due diligence before selecting a tool, a clear
              internal policy before deploying it, staff training that covers both technical use and professional obligations, and
              a review process that continues after go-live.
            </p>
            <p>
              The guidance is explicit that the legal landscape in this area is still developing. Firms that build structured,
              documented approaches now will be better positioned to adapt as the regulatory environment matures and better
              protected if their AI use is ever scrutinised.
            </p>
          </section>

          <p className="border-t border-slate-200 pt-6 text-sm text-slate-600">
            This article summarises the New Zealand Law Society&apos;s guidance &quot;Lawyers and Generative AI&quot; (March 2024). It is
            intended as general commentary only and does not constitute legal advice.
          </p>
        </div>
      </article>
    </Container>
  );
}
